### ISSUE TITLE
Gestão, Controle e Monitoramento do Projeto por meio de Issues

### ISSUE THREAD

**Issue by vinicius3w** [rcra92/x-system#3]
Vi que vocês estão utilizando o trello. O problema é que com isso a rastreabilidade das atividades de vocês fica restrita ao trello. Conforme estabelecido, as atividades, HUs, TUDO referente ao gerenciamento, controle e monitoramento do projeto deve ser feito por meio das issues no repo.

**Comment by lcs9** [comment]
Migração para o github feita
